version: '3.1'

services:
  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: easymocapui_db
    volumes:
      - ./mongodb-data:/data/db
    ports:
      - 27017:27017
  ffmpeg:
    image: linuxserver/ffmpeg